export const events = [
    {
        id: 1,
        title: 'Meeting with John',
        date: 5,
        start: '10:00 AM',
        end: '11:00 AM',
    },
    {
        id: 2,
        title: 'Lunch with Sarah',
        date: 8,
        start: '12:30 PM',
        end: '1:30 PM',
    },
    {
        id: 3,
        title: 'Phone call with Mark',
        date: 10,
        start: '2:00 PM',
        end: '2:30 PM',
    },
    {
        id: 4,
        title: 'Meeting with Jane',
        date: 12,
        start: '11:00 AM',
        end: '12:00 PM',
    },
    {
        id: 5,
        title: 'Dinner with Mike',
        date: 15,
        start: '6:30 PM',
        end: '8:00 PM',
    },
    {
        id: 6,
        title: 'Conference call',
        date: 20,
        start: '9:00 AM',
        end: '10:00 AM',
    },
    {
        id: 7,
        title: 'Meeting with Alex',
        date: 22,
        start: '3:00 PM',
        end: '4:00 PM',
    },
    {
        id: 8,
        title: 'Lunch with Steve',
        date: 24,
        start: '12:00 PM',
        end: '1:00 PM',
    },
    {
        id: 9,
        title: 'Meeting with Sarah',
        date: 28,
        start: '2:30 PM',
        end: '3:30 PM',
    },
];
